### ISSUE TITLE
Ideas/criticism list

### ISSUE THREAD

**Issue by mrhappyma** [macedonga/fbvideos#1]
**List of ideas and whatnot**

- move the "this website is open-source" banner to somewhere in the footer or faq (not too many users will probably care if your target audience is truly your average facebook user)
- it's meta now so you have to say meta in the description (currently says facebook inc.)
- the description of "where are my videos being stored" where it talks about cntrl+j - **first off it's cntrl+*shift*+j** -  could be confusing to ~~those idiots~~ people who use non-chromium browsers or macs

**Comment by macedonga** [comment]
- you're not wrong
- the actual social network is still called facebook
- it's ctrl-j

**Comment by mrhappyma** [comment]
@macedonga 
- no comment
- yes but facebook inc. no longer exists, it's now "Meta Platforms Inc.". If you want things to be legally correct you would have to change that (I meant disclaimer above sry)
- well I'm on a mac atm and cntrl+j does nothing and cmnd+j does nothing and cmd+shift+j opens the downloads page (chrome)

**Comment by macedonga** [comment]
- yes
- ohh you meant the disclaimer, yes i should change it then
- on windows it's Ctrl j... I'll have to change that
